repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_fmt
    rev: v1.105.0
    hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    id: terraform validate
    